name: jobsque_job_finder
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  # sdk: ">=2.19.6 <3.0.0"
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  awesome_dialog: ^3.1.0
  bloc: ^8.1.2
  chips_choice: ^3.0.0
  countries_flag: ^1.0.0
  country_flags: ^2.1.1
  dio: ^5.3.2
  dots_indicator: ^3.0.0
  dotted_border: ^2.0.0+3
  expand_widget: ^3.1.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.2.2
  image_picker: ^0.8.7+3
  input_history_text_field: ^0.2.0
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.3+1
  page_transition: ^2.0.9
  percent_indicator: ^4.2.3
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.1
  timer_count_down: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Icons_what_type_of_work/
    - assets/social/
    - assets/home/
    - assets/messages/
